# Generated by Django 3.2.9 on 2022-07-28 09:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(max_length=100, unique=True, validators=[django.core.validators.URLValidator(message='Введен некорректный URL-адрес')])),
                ('short_url', models.CharField(max_length=250, null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owners', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
                'ordering': ('-created',),
            },
        ),
    ]
